// Full gallery map per couple (auto-generated from public/wedding-stories)
const storyImageMap = {
  "Akshita-sourav": [
    "public/wedding-stories/Akshita-sourav/images%202/AS_01.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_02.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_03.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_04.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_05.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_06.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_07.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/AS_08.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_01.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_02.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_03.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_04.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_05.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_06.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_07.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/SA_08.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_01.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_013.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_02.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_03.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_04.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_05.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_06.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_07.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_08.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_09.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_10.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_11.jpeg",
    "public/wedding-stories/Akshita-sourav/images%202/Wed_12.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/020.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/021.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/033.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/1.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/1.webp",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/10.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/11.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/12.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/13.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/14.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/16.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/18.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/19.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/2.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/20.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/21.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/22.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/3.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/31.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/32.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/33.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/34.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/35.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/36.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/37.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/38.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/39.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/4.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/5.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/6.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/7.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/8.jpeg",
    "public/wedding-stories/Akshita-sourav/Haldi-Ring-ceremony/9.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/051.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/059.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/069.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/52.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/53.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/54.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/55.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/56.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/57.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/58.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/59.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/60.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/61.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/62.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/63.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/64.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/65.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/66.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/67.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/68.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/70.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/71.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/72.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/73.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/74.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/75.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/76.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/77.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/78.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/79.jpeg",
    "public/wedding-stories/Akshita-sourav/Wedd/80.jpeg"
  ],
  "malkit-harman": [
    "public/wedding-stories/malkit-harman/000001.jpeg",
    "public/wedding-stories/malkit-harman/0001.jpeg",
    "public/wedding-stories/malkit-harman/0016.jpeg",
    "public/wedding-stories/malkit-harman/01.jpeg",
    "public/wedding-stories/malkit-harman/016.jpeg",
    "public/wedding-stories/malkit-harman/039.jpeg",
    "public/wedding-stories/malkit-harman/10.jpeg",
    "public/wedding-stories/malkit-harman/11.jpeg",
    "public/wedding-stories/malkit-harman/12.jpeg",
    "public/wedding-stories/malkit-harman/13.jpeg",
    "public/wedding-stories/malkit-harman/14.jpeg",
    "public/wedding-stories/malkit-harman/15.jpeg",
    "public/wedding-stories/malkit-harman/16.jpeg",
    "public/wedding-stories/malkit-harman/17.jpeg",
    "public/wedding-stories/malkit-harman/18.jpeg",
    "public/wedding-stories/malkit-harman/19.jpeg",
    "public/wedding-stories/malkit-harman/2.jpeg",
    "public/wedding-stories/malkit-harman/20.jpeg",
    "public/wedding-stories/malkit-harman/21.jpeg",
    "public/wedding-stories/malkit-harman/22.jpeg",
    "public/wedding-stories/malkit-harman/23.jpeg",
    "public/wedding-stories/malkit-harman/24.jpeg",
    "public/wedding-stories/malkit-harman/25.jpeg",
    "public/wedding-stories/malkit-harman/26.jpeg",
    "public/wedding-stories/malkit-harman/27.jpeg",
    "public/wedding-stories/malkit-harman/28.jpeg",
    "public/wedding-stories/malkit-harman/29.jpeg",
    "public/wedding-stories/malkit-harman/3.jpeg",
    "public/wedding-stories/malkit-harman/31.jpeg",
    "public/wedding-stories/malkit-harman/32.jpeg",
    "public/wedding-stories/malkit-harman/33.jpeg",
    "public/wedding-stories/malkit-harman/34.jpeg",
    "public/wedding-stories/malkit-harman/35.jpeg",
    "public/wedding-stories/malkit-harman/36.jpeg",
    "public/wedding-stories/malkit-harman/37.jpeg",
    "public/wedding-stories/malkit-harman/38.jpeg",
    "public/wedding-stories/malkit-harman/39.jpeg",
    "public/wedding-stories/malkit-harman/4.jpeg",
    "public/wedding-stories/malkit-harman/40.jpeg",
    "public/wedding-stories/malkit-harman/41.jpeg",
    "public/wedding-stories/malkit-harman/43.jpeg",
    "public/wedding-stories/malkit-harman/44.jpeg",
    "public/wedding-stories/malkit-harman/5.jpeg",
    "public/wedding-stories/malkit-harman/7.jpeg",
    "public/wedding-stories/malkit-harman/8.jpeg",
    "public/wedding-stories/malkit-harman/9.jpeg",
    "public/wedding-stories/malkit-harman/90.jpeg"
  ],
  "partham-tamanna": [
    "public/wedding-stories/partham-tamanna/013.jpeg",
    "public/wedding-stories/partham-tamanna/1.jpeg",
    "public/wedding-stories/partham-tamanna/11.jpeg",
    "public/wedding-stories/partham-tamanna/12.jpeg",
    "public/wedding-stories/partham-tamanna/13.jpeg",
    "public/wedding-stories/partham-tamanna/15.jpeg",
    "public/wedding-stories/partham-tamanna/16.jpeg",
    "public/wedding-stories/partham-tamanna/18.jpeg",
    "public/wedding-stories/partham-tamanna/19.jpeg",
    "public/wedding-stories/partham-tamanna/2.jpeg",
    "public/wedding-stories/partham-tamanna/20.jpeg",
    "public/wedding-stories/partham-tamanna/21.jpeg",
    "public/wedding-stories/partham-tamanna/22.jpeg",
    "public/wedding-stories/partham-tamanna/23.jpeg",
    "public/wedding-stories/partham-tamanna/24.jpeg",
    "public/wedding-stories/partham-tamanna/25.jpeg",
    "public/wedding-stories/partham-tamanna/26.jpeg",
    "public/wedding-stories/partham-tamanna/27.jpeg",
    "public/wedding-stories/partham-tamanna/28.jpeg",
    "public/wedding-stories/partham-tamanna/29.jpeg",
    "public/wedding-stories/partham-tamanna/3.jpeg",
    "public/wedding-stories/partham-tamanna/30.jpeg",
    "public/wedding-stories/partham-tamanna/31.jpeg",
    "public/wedding-stories/partham-tamanna/32.jpeg",
    "public/wedding-stories/partham-tamanna/33.jpeg",
    "public/wedding-stories/partham-tamanna/35.jpeg",
    "public/wedding-stories/partham-tamanna/36.jpeg",
    "public/wedding-stories/partham-tamanna/37.jpeg",
    "public/wedding-stories/partham-tamanna/38.jpeg",
    "public/wedding-stories/partham-tamanna/39.jpeg",
    "public/wedding-stories/partham-tamanna/4.jpeg",
    "public/wedding-stories/partham-tamanna/5.jpeg",
    "public/wedding-stories/partham-tamanna/6.jpeg"
  ],
  "punit-varsha": [
    "public/wedding-stories/punit-varsha/PV%20(1).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(10).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(11).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(12).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(13).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(14).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(15).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(16).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(2).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(3).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(4).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(5).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(6).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(7).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(8).jpeg",
    "public/wedding-stories/punit-varsha/PV%20(9).jpeg"
  ],
  "Samkit": [
    "public/wedding-stories/Samkit/1.jpeg",
    "public/wedding-stories/Samkit/10.jpeg",
    "public/wedding-stories/Samkit/11.jpeg",
    "public/wedding-stories/Samkit/12.jpeg",
    "public/wedding-stories/Samkit/13.jpeg",
    "public/wedding-stories/Samkit/14.jpeg",
    "public/wedding-stories/Samkit/15.jpeg",
    "public/wedding-stories/Samkit/16.jpeg",
    "public/wedding-stories/Samkit/17.jpeg",
    "public/wedding-stories/Samkit/18.jpeg",
    "public/wedding-stories/Samkit/19.jpeg",
    "public/wedding-stories/Samkit/2.jpeg",
    "public/wedding-stories/Samkit/20.jpeg",
    "public/wedding-stories/Samkit/21.jpeg",
    "public/wedding-stories/Samkit/22.jpeg",
    "public/wedding-stories/Samkit/23.jpeg",
    "public/wedding-stories/Samkit/24.jpeg",
    "public/wedding-stories/Samkit/25.jpeg",
    "public/wedding-stories/Samkit/26.jpeg",
    "public/wedding-stories/Samkit/27.jpeg",
    "public/wedding-stories/Samkit/28.jpeg",
    "public/wedding-stories/Samkit/29.jpeg",
    "public/wedding-stories/Samkit/3.jpeg",
    "public/wedding-stories/Samkit/30.jpeg",
    "public/wedding-stories/Samkit/31.jpeg",
    "public/wedding-stories/Samkit/32.jpeg",
    "public/wedding-stories/Samkit/33.jpeg",
    "public/wedding-stories/Samkit/34.jpeg",
    "public/wedding-stories/Samkit/35.jpeg",
    "public/wedding-stories/Samkit/36.jpeg",
    "public/wedding-stories/Samkit/4.jpeg",
    "public/wedding-stories/Samkit/5.jpeg",
    "public/wedding-stories/Samkit/6.jpeg",
    "public/wedding-stories/Samkit/7.jpeg",
    "public/wedding-stories/Samkit/8.jpeg",
    "public/wedding-stories/Samkit/9.jpeg"
  ],
  "Shikha": [
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_01.jpeg",
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_02.jpeg",
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_03.jpeg",
    "public/wedding-stories/Shikha/Ring%20Ceremony/SS_04.jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(1).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(10).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(11).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(12).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(13).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(2).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(3).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(4).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(5).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(6).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(7).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(8).jpeg",
    "public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(9).jpeg"
  ],
  "vaibhav-bhawna": [
    "public/wedding-stories/vaibhav-bhawna/1.jpeg",
    "public/wedding-stories/vaibhav-bhawna/11.jpeg",
    "public/wedding-stories/vaibhav-bhawna/12.jpeg",
    "public/wedding-stories/vaibhav-bhawna/13.jpeg",
    "public/wedding-stories/vaibhav-bhawna/14.jpeg",
    "public/wedding-stories/vaibhav-bhawna/15.jpeg",
    "public/wedding-stories/vaibhav-bhawna/16.jpeg",
    "public/wedding-stories/vaibhav-bhawna/17.jpeg",
    "public/wedding-stories/vaibhav-bhawna/18.jpeg",
    "public/wedding-stories/vaibhav-bhawna/19.jpeg",
    "public/wedding-stories/vaibhav-bhawna/2.jpeg",
    "public/wedding-stories/vaibhav-bhawna/20.jpeg",
    "public/wedding-stories/vaibhav-bhawna/21.jpeg",
    "public/wedding-stories/vaibhav-bhawna/22.jpeg",
    "public/wedding-stories/vaibhav-bhawna/23.jpeg",
    "public/wedding-stories/vaibhav-bhawna/24.jpeg",
    "public/wedding-stories/vaibhav-bhawna/25.jpeg",
    "public/wedding-stories/vaibhav-bhawna/26.jpeg",
    "public/wedding-stories/vaibhav-bhawna/27.jpeg",
    "public/wedding-stories/vaibhav-bhawna/28.jpeg",
    "public/wedding-stories/vaibhav-bhawna/29.jpeg",
    "public/wedding-stories/vaibhav-bhawna/3.jpeg",
    "public/wedding-stories/vaibhav-bhawna/4.jpeg",
    "public/wedding-stories/vaibhav-bhawna/5.jpeg",
    "public/wedding-stories/vaibhav-bhawna/6.jpeg"
  ]
};

const preWeddingStoryImageMap = {
  'jeet-deep': [
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/1.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/2.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/3.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/4.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/5.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/6.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/7.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/8.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/9.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/10.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/11.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/12.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/13.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/14.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/15.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/16.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/17.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/18.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/19.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/20.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/21.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/22.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/23.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/24.jpeg',
    'public/prewed-stories/Jeet-deep(Lal Haweli,-Nabha)/25.jpeg'
  ],
  kolkata: [
    'public/prewed-stories/Kolkata/1.jpeg',
    'public/prewed-stories/Kolkata/2.jpeg',
    'public/prewed-stories/Kolkata/3.jpeg',
    'public/prewed-stories/Kolkata/4.jpeg',
    'public/prewed-stories/Kolkata/5.jpeg',
    'public/prewed-stories/Kolkata/6.jpeg',
    'public/prewed-stories/Kolkata/7.jpeg',
    'public/prewed-stories/Kolkata/8.jpeg',
    'public/prewed-stories/Kolkata/9.jpeg'
  ],
  'punit-varsha-pre': [
    'public/prewed-stories/punit-varsha(Jaipur)/1.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/2.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/3.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/4.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/5.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/6.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/7.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/8.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/9.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/10.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/11.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/12.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/14.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/15.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/16.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/17.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/18.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/19.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/20.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/21.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/22.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/23.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/24.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/25.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/26.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/27.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/28.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/29.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/30.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/31.jpeg',
    'public/prewed-stories/punit-varsha(Jaipur)/88.jpeg'
  ],
  'ricky-parul': [
    'public/prewed-stories/ricky-parul (Manali)/03.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/1.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/2.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/3.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/4.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/5.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/6.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/7.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/8.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/9.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/10.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/11.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/12.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/13.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/14.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/15.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/16.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/17.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/18.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/19.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/20.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/21.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/22.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/23.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/24.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/25.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/26.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/27.jpeg',
    'public/prewed-stories/ricky-parul (Manali)/28.jpeg'
  ],
  'samkit-tina': [
    'public/prewed-stories/samkit-tina(Goa)/1.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/2.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/3.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/4.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/5.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/6.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/7.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/8.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/9.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/10.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/11.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/12.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/13.jpeg',
    'public/prewed-stories/samkit-tina(Goa)/14.jpeg'
  ],
  'vaibhav-bhawna-pre': [
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/1.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/2.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/3.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/4.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/5.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/6.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/7.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/8.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/9.jpeg',
    'public/prewed-stories/Vaibhav-bhawana(Dumping-Yard,Jaipur)/10.jpeg'
  ]
};

const storiesData = [
  {
    id: 'akshita-sourav',
    slug: 'akshita-sourav',
    type: 'wedding',
    coupleName: 'Akshita & Sourav',
    location: 'Hisar, India',
    date: 'Winter 2024',
    heroImage: 'public/wedding-stories/Akshita-sourav/images%202/Wed_01.jpeg',
    excerpt: 'Three days of haldi hues, baraat energy, and regal pheras captured across Hisar.',
    fullStory: 'Akshita and Sourav celebrated every ritual with contagious joy. From turmeric drenched haldi frames to an opulent wedding night, their story is a timeless tribute to Punjabi grandeur.',
    images: storyImageMap['Akshita-sourav'],
  },
  {
    id: 'malkit-harman',
    slug: 'malkit-harman',
    type: 'wedding',
    coupleName: 'Malkit & Harman',
    location: 'Ludhiana, Punjab',
    date: 'Autumn 2024',
    heroImage: 'public/wedding-stories/malkit-harman/01.jpeg',
    excerpt: 'Classic Sikh traditions with modern styling, set inside a candle-lit gurudwara.',
    fullStory: 'Malkit and Harman trusted us to document each emotion—from quiet ardaas moments to their explosive dance floor. The result is a visual diary overflowing with warmth and metallic hues.',
    images: storyImageMap['malkit-harman'],
  },
  {
    id: 'partham-tamanna',
    slug: 'partham-tamanna',
    type: 'wedding',
    coupleName: 'Partham & Tamanna',
    location: 'Gurugram, India',
    date: 'Monsoon 2024',
    heroImage: 'public/wedding-stories/partham-tamanna/1.jpeg',
    excerpt: 'A pastel-soaked cocktail night that led straight into an effervescent wedding day.',
    fullStory: 'Urban luxury met heartfelt rituals for Partham and Tamanna. Every event transitioned seamlessly—sangeet, pheras, and vidaai—while we crafted layered visuals around their chemistry.',
    images: storyImageMap['partham-tamanna'],
  },
  {
    id: 'punit-varsha',
    slug: 'punit-varsha',
    type: 'wedding',
    coupleName: 'Punit & Varsha',
    location: 'Jaipur, Rajasthan',
    date: 'Summer 2024',
    heroImage: 'public/wedding-stories/punit-varsha/PV%20(1).jpeg',
    excerpt: 'Intimate palace nuptials with champagne-toned decor and dancing till dawn.',
    fullStory: 'Punit and Varsha\'s guest list was small but the emotions were colossal. We focused on quiet in-between moments, dreamy couple portraits, and every sparkle from their rooftop reception.',
    images: storyImageMap['punit-varsha'],
  },
  {
    id: 'samkit-naina',
    slug: 'samkit-naina',
    type: 'wedding',
    coupleName: 'Samkit & Naina',
    location: 'New Delhi, India',
    date: 'Spring 2024',
    heroImage: 'public/wedding-stories/Samkit/1.jpeg',
    excerpt: 'A sundowner pheras ceremony overlooking the city skyline and drenched in floral pastels.',
    fullStory: 'Samkit and Naina\'s celebrations flowed from choreographed sangeet acts to an airy mandap filled with baby\'s breath. We leaned into candid framing and cinematic silhouettes.',
    images: storyImageMap['Samkit'],
  },
  {
    id: 'shikha-sarthak',
    slug: 'shikha-sarthak',
    type: 'wedding',
    coupleName: 'Shikha & Sarthak',
    location: 'Chandigarh, India',
    date: 'February 2025',
    heroImage: 'public/wedding-stories/Shikha/Shikha%20wedding_/SSq%20(1).jpeg',
    excerpt: 'Velvet lehengas, mirror-work sherwanis, and a baraat that lit up the entire sector.',
    fullStory: 'Shikha and Sarthak wanted a fashion-forward wedding story. We paired editorial lighting with documentary coverage to showcase their statement outfits and heartfelt rituals.',
    images: storyImageMap['Shikha'],
  },
  {
    id: 'vaibhav-bhawna',
    slug: 'vaibhav-bhawna',
    type: 'wedding',
    coupleName: 'Vaibhav & Bhawna',
    location: 'Hisar, India',
    date: 'January 2025',
    heroImage: 'public/wedding-stories/vaibhav-bhawna/1.jpeg',
    excerpt: 'A cosy hometown wedding overflowing with family rituals, laughter, and dhol beats.',
    fullStory: 'Vaibhav and Bhawna kept each function rooted in tradition. We photographed every blessing, every sibling prank, and every tender glance that made their wedding unforgettable.',
    images: storyImageMap['vaibhav-bhawna'],
  },
  {
    id: 'jeet-deep-prewedding',
    slug: 'jeet-deep-lal-haweli-nabha',
    type: 'pre-wedding',
    coupleName: 'Jeet & Deep',
    location: 'Lal Haweli, Nabha',
    date: 'Luxury Pre-Wedding 2024',
    heroImage: preWeddingStoryImageMap['jeet-deep'][0],
    excerpt: 'Editorial pre-wedding photography in Hisar vibes with royal corridors, veils, and classic cars at Lal Haweli, Nabha.',
    fullStory: 'Jeet and Deep travelled from Hisar to Lal Haweli, Nabha for a heritage-inspired pre-wedding session. We paired couture wardrobes with natural laughter to craft frames filled with arches, reflections, and cinematic storytelling that still feel unmistakably Hisar.',
    images: preWeddingStoryImageMap['jeet-deep'],
  },
  {
    id: 'kolkata-prewedding',
    slug: 'kolkata-prewedding',
    type: 'pre-wedding',
    coupleName: 'Kolkata Pre-Wedding Story',
    location: 'Kolkata, India',
    date: 'Cultural Escape 2024',
    heroImage: preWeddingStoryImageMap['kolkata'][0],
    excerpt: 'Sunrise ferries, vintage streets, and nostalgic pre-wedding photography in Hisar style across Kolkata.',
    fullStory: 'This Hisar couple wanted their pre-wedding photographs to mirror the poetry of Kolkata. From Howrah Bridge breezes to pastel colonial walls, we stayed true to our Luxury Photography & Film Company roots while highlighting their chemistry and the city’s timeless charm.',
    images: preWeddingStoryImageMap['kolkata'],
  },
  {
    id: 'punit-varsha-prewedding',
    slug: 'punit-varsha-jaipur-prewedding',
    type: 'pre-wedding',
    coupleName: 'Punit & Varsha',
    location: 'Jaipur, Rajasthan',
    date: 'Desert Sundowner 2024',
    heroImage: preWeddingStoryImageMap['punit-varsha-pre'][0],
    excerpt: 'Couture silhouettes, sandstone textures, and romantic pre-wedding photography in Hisar hues across Jaipur.',
    fullStory: 'Before their wedding, Punit and Varsha invited us to craft a Jaipur pre-wedding story. We mixed drone frames, city palace geometry, and tender close-ups so their Hisar family could feel every moment back home.',
    images: preWeddingStoryImageMap['punit-varsha-pre'],
  },
  {
    id: 'ricky-parul-prewedding',
    slug: 'ricky-parul-manali-prewedding',
    type: 'pre-wedding',
    coupleName: 'Ricky & Parul',
    location: 'Manali, Himachal Pradesh',
    date: 'Alpine Escape 2024',
    heroImage: preWeddingStoryImageMap['ricky-parul'][0],
    excerpt: 'Evergreen forests, misty peaks, and playful couple poses define this Manali pre-wedding photography in Hisar signature style.',
    fullStory: 'Ricky and Parul trusted our Hisar photography team to bring cinematic flair to Manali. From cosy cabins to riverside strolls, we leaned into natural light and motion to showcase their chemistry against dramatic mountain backdrops.',
    images: preWeddingStoryImageMap['ricky-parul'],
  },
  {
    id: 'samkit-tina-prewedding',
    slug: 'samkit-tina-goa-prewedding',
    type: 'pre-wedding',
    coupleName: 'Samkit & Tina',
    location: 'Goa, India',
    date: 'Coastal Romance 2024',
    heroImage: preWeddingStoryImageMap['samkit-tina'][0],
    excerpt: 'Sun-drenched beaches, palms, and velvety nightscapes define this Goa pre-wedding shot for our Hisar couple.',
    fullStory: 'Samkit and Tina wanted a carefree coastal story before their wedding ceremonies. We captured champagne toasts, barefoot walks, and moody neon portraits—proof that the best wedding photography in Hisar can travel anywhere.',
    images: preWeddingStoryImageMap['samkit-tina'],
  },
  {
    id: 'vaibhav-bhawna-prewedding',
    slug: 'vaibhav-bhawna-dumping-yard-prewedding',
    type: 'pre-wedding',
    coupleName: 'Vaibhav & Bhawna',
    location: 'Dumping Yard, Jaipur',
    date: 'Editorial Desert 2024',
    heroImage: preWeddingStoryImageMap['vaibhav-bhawna-pre'][0],
    excerpt: 'Bold desert dunes, earthy textures, and fashion-forward pre-wedding photography in Hisar colour palettes.',
    fullStory: 'For their pre-wedding story, Vaibhav and Bhawna swapped Hisar streets for Jaipur’s Dumping Yard. We leaned into golden hour silhouettes, sweeping veils, and movement-driven poses to complement their understated chemistry.',
    images: preWeddingStoryImageMap['vaibhav-bhawna-pre'],
  }
];

function getStoryBySlug(slug) {
  return storiesData.find(story => story.slug === slug);
}

function getStoriesByType(type = 'all') {
  if (type === 'all') return storiesData;
  return storiesData.filter(story => story.type === type);
}

if (typeof window !== 'undefined') {
  window.storiesData = storiesData;
  window.getStoryBySlug = getStoryBySlug;
  window.getStoriesByType = getStoriesByType;
}
